/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { IconKind, } from "./components/icon/interface";
export namespace Components {
    interface ResumeApp {
    }
    interface ScrollTop {
    }
    interface UiIcon {
        "glyph": string;
        "kind": IconKind;
    }
}
declare global {
    interface HTMLResumeAppElement extends Components.ResumeApp, HTMLStencilElement {
    }
    var HTMLResumeAppElement: {
        prototype: HTMLResumeAppElement;
        new (): HTMLResumeAppElement;
    };
    interface HTMLScrollTopElement extends Components.ScrollTop, HTMLStencilElement {
    }
    var HTMLScrollTopElement: {
        prototype: HTMLScrollTopElement;
        new (): HTMLScrollTopElement;
    };
    interface HTMLUiIconElement extends Components.UiIcon, HTMLStencilElement {
    }
    var HTMLUiIconElement: {
        prototype: HTMLUiIconElement;
        new (): HTMLUiIconElement;
    };
    interface HTMLElementTagNameMap {
        "resume-app": HTMLResumeAppElement;
        "scroll-top": HTMLScrollTopElement;
        "ui-icon": HTMLUiIconElement;
    }
}
declare namespace LocalJSX {
    interface ResumeApp {
    }
    interface ScrollTop {
    }
    interface UiIcon {
        "glyph"?: string;
        "kind"?: IconKind;
    }
    interface IntrinsicElements {
        "resume-app": ResumeApp;
        "scroll-top": ScrollTop;
        "ui-icon": UiIcon;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "resume-app": LocalJSX.ResumeApp & JSXBase.HTMLAttributes<HTMLResumeAppElement>;
            "scroll-top": LocalJSX.ScrollTop & JSXBase.HTMLAttributes<HTMLScrollTopElement>;
            "ui-icon": LocalJSX.UiIcon & JSXBase.HTMLAttributes<HTMLUiIconElement>;
        }
    }
}
