/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { IconKind, } from "./components/icon/interface";
export namespace Components {
    interface AppRoot {
    }
    interface ScrollTop {
    }
    interface UiDashboard {
        "loading": boolean;
    }
    interface UiIcon {
        "glyph": string;
        "kind": IconKind;
    }
    interface UiResume {
    }
}
declare global {
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLScrollTopElement extends Components.ScrollTop, HTMLStencilElement {
    }
    var HTMLScrollTopElement: {
        prototype: HTMLScrollTopElement;
        new (): HTMLScrollTopElement;
    };
    interface HTMLUiDashboardElement extends Components.UiDashboard, HTMLStencilElement {
    }
    var HTMLUiDashboardElement: {
        prototype: HTMLUiDashboardElement;
        new (): HTMLUiDashboardElement;
    };
    interface HTMLUiIconElement extends Components.UiIcon, HTMLStencilElement {
    }
    var HTMLUiIconElement: {
        prototype: HTMLUiIconElement;
        new (): HTMLUiIconElement;
    };
    interface HTMLUiResumeElement extends Components.UiResume, HTMLStencilElement {
    }
    var HTMLUiResumeElement: {
        prototype: HTMLUiResumeElement;
        new (): HTMLUiResumeElement;
    };
    interface HTMLElementTagNameMap {
        "app-root": HTMLAppRootElement;
        "scroll-top": HTMLScrollTopElement;
        "ui-dashboard": HTMLUiDashboardElement;
        "ui-icon": HTMLUiIconElement;
        "ui-resume": HTMLUiResumeElement;
    }
}
declare namespace LocalJSX {
    interface AppRoot {
    }
    interface ScrollTop {
    }
    interface UiDashboard {
        "loading"?: boolean;
    }
    interface UiIcon {
        "glyph"?: string;
        "kind"?: IconKind;
    }
    interface UiResume {
    }
    interface IntrinsicElements {
        "app-root": AppRoot;
        "scroll-top": ScrollTop;
        "ui-dashboard": UiDashboard;
        "ui-icon": UiIcon;
        "ui-resume": UiResume;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "scroll-top": LocalJSX.ScrollTop & JSXBase.HTMLAttributes<HTMLScrollTopElement>;
            "ui-dashboard": LocalJSX.UiDashboard & JSXBase.HTMLAttributes<HTMLUiDashboardElement>;
            "ui-icon": LocalJSX.UiIcon & JSXBase.HTMLAttributes<HTMLUiIconElement>;
            "ui-resume": LocalJSX.UiResume & JSXBase.HTMLAttributes<HTMLUiResumeElement>;
        }
    }
}
